server:
  port: 9000

#mysql
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sportPlay
      username: root
      password: 123456



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zhstzzy/dao/*.xml
  type-aliases-package: com.zhstzzy.model


