server:
  port: 9000

#mysql
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sportPlay?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  mail:
    host: smtp.qq.com
    port:
    username: 210477243@qq.com
    password: msmlefhmzjwabici
    from: 210477243@qq.com
    default-encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  #  输出日志信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: com.zhstzzy.model
logging:
  level:
    com.zhstzzy.mapper: debug